### ISSUE TITLE
Test table

### ISSUE THREAD

**Issue by jverkoey** [material-motion/material-motion#36]
## Android platform support

| Library | Build status | Coverage | Version | Issues |
|---------|:------------:|:--------:|:-------:|:------:|
| [catalog-android](https://github.com/material-motion/catalog-android/) |  |  |  | 0 open |
| [conventions-android](https://github.com/material-motion/conventions-android/) |  |  |  | 0 open |
| [experiments-android](https://github.com/material-motion/experiments-android/) |  |  |  | 0 open |
| [expression-android](https://github.com/material-motion/expression-android/) |  |  |  | 2 open |
| [family-direct-manipulation-android](https://github.com/material-motion/family-direct-manipulation-android/) | passing | 100% | v1.2.0 | 2 open |
| [family-rebound-android](https://github.com/material-motion/family-rebound-android/) | passing | 100% | v1.1.0 | 3 open |
| [family-tween-android](https://github.com/material-motion/family-tween-android/) | passing | 100% | v2.1.0 | 2 open |
| [gestures-android](https://github.com/material-motion/gestures-android/) | passing | 95% | v1.0.0 | 2 open |
| [indefinite-observable-android](https://github.com/material-motion/indefinite-observable-android/) |  |  | v1.0.0 | 0 open |
| [runtime-android](https://github.com/material-motion/runtime-android/) | passing | 99% | v6.0.1 | 11 open |
| [streams-android](https://github.com/material-motion/streams-android/) |  |  |  | 0 open |
| [transitions-android](https://github.com/material-motion/transitions-android/) |  |  |  | 9 open |

## Apple platform support

| Library | Build status | Coverage | Version | Platforms | Docs | Issues |
|---------|:------------:|:--------:|:-------:|:---------:|:----:|:------:|
| [catalog-swift](https://github.com/material-motion/catalog-swift) | passing |  |  |  |  | 10 open |
| [conventions-objc](https://github.com/material-motion/conventions-objc) |  |  |  |  |  | 0 open |
| [coreanimation-swift](https://github.com/material-motion/coreanimation-swift) | passing | 61% | v2.0.0 | ios |  | 6 open |
| [coreanimation-transitions-swift](https://github.com/material-motion/coreanimation-transitions-swift) | passing | 84% | v1.0.0 | ios | -1% | 0 open |
| [direct-manipulation-swift](https://github.com/material-motion/direct-manipulation-swift) | passing | 84% | v1.1.0 | ios |  | 5 open |
| [indefinite-observable-swift](https://github.com/material-motion/indefinite-observable-swift) | passing | 100% | v2.0.0 | ios / osx | 50% | 2 open |
| [pop-swift](https://github.com/material-motion/pop-swift) | passing | 42% | v1.1.0 | ios | 21% | 6 open |
| [pop-transitions-swift](https://github.com/material-motion/pop-transitions-swift) | passing | 71% | v1.0.0 | ios |  | 0 open |
| [runtime-objc](https://github.com/material-motion/runtime-objc) | passing | 91% | v6.0.1 | ios | 100% | 16 open |
| [streams-swift](https://github.com/material-motion/streams-swift) |  |  |  |  |  | 5 open |
| [transitions-objc](https://github.com/material-motion/transitions-objc) | passing | 48% | v1.1.0 | ios | 90% | 5 open |

## Web platform support

| Library | Build status | Coverage | Version | Issues |
|---------|:------------:|:--------:|:-------:|:------:|
| [indefinite-observable-js](https://github.com/material-motion/indefinite-observable-js) |  |  | v0.1.0 | 4 open |
| [material-motion-js](https://github.com/material-motion/material-motion-js) |  |  |  | 48 open |
| [streams-experiment-js](https://github.com/material-motion/streams-experiment-js) |  |  |  | 1 open |

## Misc libraries

| Library | Build status | Coverage | Version | Issues |
|---------|:------------:|:--------:|:-------:|:------:|
| [apidiff](https://github.com/material-motion/apidiff/) | passing | 86% | v1.0.0 | 10 open |
| [chrome-inspector](https://github.com/material-motion/chrome-inspector/) |  |  |  | 4 open |
| [direct-web](https://github.com/material-motion/direct-web/) |  |  |  | 0 open |
| [hubot](https://github.com/material-motion/hubot/) |  |  |  | 0 open |
| [material-motion](https://github.com/material-motion/material-motion/) |  |  |  | 16 open |
| [milemarker](https://github.com/material-motion/milemarker/) |  |  |  | 18 open |
| [sprints](https://github.com/material-motion/sprints/) |  |  |  | 32 open |
| [starmap](https://github.com/material-motion/starmap/) |  |  |  | 44 open |
| [sublime](https://github.com/material-motion/sublime/) |  |  |  | 0 open |
| [tools](https://github.com/material-motion/tools/) |  |  |  | 93 open |

**Comment by appsforartists** [comment]
your headings are in the wrong order sir

but congrats on making it this far.  😃

**Comment by jverkoey** [comment]
All because of you good sir!

**Comment by jverkoey** [comment]
Signin' out for the eve, see y'all on the other side!

**Comment by appsforartists** [comment]
DOO IT.  i should too.

**Comment by appsforartists** [comment]
there's no flattery emoji on github reactions
