### ISSUE TITLE
Break IndefiniteObservable docs up into smaller pieces

### ISSUE THREAD

**Issue by jverkoey** [material-motion/material-motion#39]
https://material-motion.github.io/material-motion/documentation/L4/IndefiniteObservable

IndefiniteObservable
1. Introduction
2. Operators
3. makeOperator

Advanced topics

1. Producers and Sources: Connecting to existing event systems
2. Multicasting

**Comment by jverkoey** [comment]
Emphasis on providing an introduction that explains why this pattern is important.

**Comment by appsforartists** [comment]
I'm all for making the docs the best they can be, and if refactoring the walkthrough helps, let's do it.  But, I also want to make sure we're tailoring towards the right audience.  That walkthrough is "let's understand observables from the ground up."  We could probably have something more approachable for the other knowledge levels.

**Comment by jverkoey** [comment]
My main concern is the length of the document and the number of concepts it introduced. Breaking it into pieces would help limit the cognitive load to someone new.
