### ISSUE TITLE
Update testing/javascript

### ISSUE THREAD

**Issue by jverkoey** [material-motion/material-motion#40]
https://material-motion.github.io/material-motion/team/essentials/testing/javascript

I believe we now have a recommended testing solution for javascript. Let's update our team docs accordingly.

**Comment by appsforartists** [comment]
Thanks for the reminder.  Let's add this to the end of @tofuless's testing cleanup.

**Comment by appsforartists** [comment]
dammit, i can't add this to his milestone because it's in a different repo.  🙄

**Comment by appsforartists** [comment]
and I can't tag him in it either, because he isn't core

**Comment by jverkoey** [comment]
You can add the relevant issue to the sprint planning board if that's helpful.

**Comment by jverkoey** [comment]
https://github.com/orgs/material-motion/projects/4?fullscreen=true

**Comment by appsforartists** [comment]
Thanks.  Maybe next week.  :)
