### ISSUE TITLE
Bottom sheet

### ISSUE THREAD

**Issue by appsforartists** [material-motion/material-motion#64]
![bottom-sheet](https://cloud.githubusercontent.com/assets/926648/21788384/4c96e22a-d683-11e6-844a-a0c641f6ef0b.gif)

**Comment by appsforartists** [comment]
Demo will live here: https://material-motion-demos.firebaseapp.com/bottom-sheet/

**Comment by jverkoey** [comment]
Bad url

**Comment by appsforartists** [comment]
@pingpongboss here's the album art I used:

https://material-motion-demos.firebaseapp.com/images/album-art.png
