### ISSUE TITLE
Should a completely unsubscribed _remember purge its last information?

### ISSUE THREAD

**Issue by jverkoey** [material-motion/material-motion#68]
Repro:

```swift
let observable = MotionObservable<Int> { observer in
  observer.next(1)
  observer.next(2)
  observer.next(3)
  return noopDisconnect
}
```

1. First observer connects. Receives last value.
2. Second observer connects. Receives last value.
3. Both observers disconnect.
4. Third observer connects. **Should it receive the last cached value?**

**Comment by jverkoey** [comment]
This likely isn't an issue.

**Comment by appsforartists** [comment]
The solution for this is simple (inside `disconnect`'s `observers.size` test, clear `lastValue`).  However, that would make the behavior experienced by one observer dependent on the behavior of another (e.g. only `lastValue` is cached if there are other live subscriptions).

I think the system will be easier to use if we can minimize conditional behavior, so I'm 👍 for punting on this until we have a concrete problem that stems from it.  Hopefully by then, we'll also have a corpus of examples to verify that the change doesn't break real uses.
