### ISSUE TITLE
Should an Interaction have only one stream? Or one stream per target?

### ISSUE THREAD

**Issue by pingpongboss** [material-motion/material-motion#70]
**Pros of one stream per target:**
Each `runtime.add(interaction, target)` results in a new stream.
Each `runtime.add(interaction, target)` results in a new underlying system (core animation) being invoked.

**Pros of only one stream:**
In nested interactions, a master interaction often wants to access the stream of a slave interaction.
Simpler to reason about. See https://github.com/material-motion/material-motion-swift/issues/76 as an example of one stream being an assumption.

**Comment by jverkoey** [comment]
This will be resolved by https://github.com/material-motion/material-motion/issues/72
